### ISSUE TITLE
网络资讯面板无法使用， 显示Untitled Panel

### ISSUE THREAD

**Issue by ZeroX1ng** [Nebulosa-Cat/Surge#10]
查看错误日志发现提示：
![e4d2f6456b986953f1a3a5c2b57cbe8](https://user-images.githubusercontent.com/34992990/183240319-26a931da-fc0e-4495-b2ff-e484a67d9405.jpg)
请问这是什么原因导致呢？
设备是ios14.2 12pm，最新版surge

**Comment by Nebulosa-Cat** [comment]
> 查看错误日志发现提示：
> 
> ![e4d2f6456b986953f1a3a5c2b57cbe8](https://user-images.githubusercontent.com/34992990/183240319-26a931da-fc0e-4495-b2ff-e484a67d9405.jpg)
> 
> 请问这是什么原因导致呢？
> 
> 设备是ios14.2 12pm，最新版surge

商店版還是TestFlight
是否有面板畫面的截圖？

**Comment by ZeroX1ng** [comment]
![a8074467737354e57bd457a11dffd0d](https://user-images.githubusercontent.com/34992990/183240598-f23eefa1-8935-4044-8c07-d056168f9f3d.jpg)
![acd54ae3aa18d4fa9ebcb10c93e5cd5](https://user-images.githubusercontent.com/34992990/183240605-94df1034-d11d-49ba-ac9b-29abb70cec98.jpg)
![4eae746d3e57b4d111970b8edbe5919](https://user-images.githubusercontent.com/34992990/183240610-e5daaad5-68a9-4c2e-ad41-919ede8d40fd.jpg)
![5fc0db42088f0d6aaef77d2cf30a7f4](https://user-images.githubusercontent.com/34992990/183240611-e814d716-7330-4e2b-96e7-159905174e38.jpg)

目前是商店版本V4.15.0

**Comment by Nebulosa-Cat** [comment]
@ZeroX1ng 你有辦法用腳本編輯器把 networkCheck_cn.js 這個腳本截圖發一下嗎?
我看一下內容是否和我這邊一樣

因為這個錯誤我這邊復現不出來

**Comment by ZeroX1ng** [comment]
![image](https://user-images.githubusercontent.com/34992990/183242569-7a9e346e-3b13-4033-ab58-082ab035b181.jpeg)

**Comment by Nebulosa-Cat** [comment]
> ![image](https://user-images.githubusercontent.com/34992990/183242569-7a9e346e-3b13-4033-ab58-082ab035b181.jpeg)
> 
> 脚本编辑器里运行一样提示上面的line 58报错

你去日誌那邊，應該會看到很多檔案，找到 Editor-2022-08-06.log 那個截個圖
裡面可能會有程式本身的紀錄

如果太多找不到的話滑到最下面"刪除全部日誌"，然後在編輯器執行一次應該就會出現了
如果有 net-info-panel.js-2022-08-06.log 也截圖一併發上來 (這個 log 檔是要在面板那邊有執行過才會產生的)

**Comment by ZeroX1ng** [comment]
17:15:16.261694 An exception was catched while evaluate script Untitled: SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.. Line number 58, column: (null)
17:15:16.265588 [Script Aborted]
----------------------------
17:18:17.444565 An exception was catched while evaluate script Untitled: SyntaxError: Unexpected token '='. Expected an opening '(' before a method's parameter list.. Line number 58, column: (null)
17:18:17.445842 [Script Aborted]
----------------------------

**Comment by Nebulosa-Cat** [comment]
@ZeroX1ng 不是這個
是這邊
![image](https://user-images.githubusercontent.com/30948446/183242960-52cb82a5-d590-4b0d-b223-28631746eafb.jpeg)
然後點進去
![image](https://user-images.githubusercontent.com/30948446/183242976-247367cc-4e72-4eea-8929-981be04bbb08.png)
找到要的 log 檔
![image](https://user-images.githubusercontent.com/30948446/183242982-65843471-d9e4-4bec-94ce-93c9344a6a5d.png)

**Comment by Nebulosa-Cat** [comment]
你貼的那個應該是事件，不是日誌紀錄

**Comment by ZeroX1ng** [comment]
![b7033e05581ac1614e0d59ec14353e6](https://user-images.githubusercontent.com/34992990/183243060-ea882033-9a1f-4f02-9a08-073867260e8d.jpg)
![4928b588adfd8154d64413f721a1f85](https://user-images.githubusercontent.com/34992990/183243065-ef032e6c-6bd7-4f00-8ff2-5c18bf1cac8b.jpg)
Editor的的就是上面发的，我要崩溃了，都是这个提示

**Comment by hirakujira** [comment]
感謝你的回報，經排查是因為腳本裡面 JS 語法要求的系統版本比較高
目前已經修改向下支援，我測 13.5 可以用了，你 14.2 應該也沒問題
再麻煩試試看，謝謝

**Comment by ZeroX1ng** [comment]
感谢更新，确实可以正确使用了
